const {app,dialog,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{header}=require('../electron/recordings.cjs');
app.disableHardwareAcceleration();const temp=fs.mkdtempSync(path.join(os.tmpdir(),'voice-studio-ui-'));app.setPath('appData',temp);app.setPath('userData',path.join(temp,'VOICE'));const root=path.join(temp,'VOICE','Recordings');fs.mkdirSync(root,{recursive:true});const id=randomUUID(),file=path.join(root,id+'.wav'),pcm=Buffer.alloc(48000*4*2);for(let i=0;i<pcm.length/2;i++){const t=i/48000,amp=(t>.5&&t<1.2)||(t>2.3&&t<3.5)?.2:0;pcm.writeInt16LE(Math.round(Math.sin(t*880*Math.PI)*amp*32767),i*2);}fs.writeFileSync(file,Buffer.concat([header(pcm.length,48000),pcm]));const original=fs.readFileSync(file);
const project=path.join(temp,'BRINK'),cine=path.join(temp,'Voice.brinkvideo');fs.mkdirSync(project);fs.writeFileSync(path.join(project,'project.json'),'{}');dialog.showMessageBox=async()=>({response:1});dialog.showOpenDialog=async(_,options)=>({canceled:false,filePaths:[options.properties.includes('openDirectory')?project:file]});dialog.showSaveDialog=async()=>({canceled:false,filePath:cine});
const errors=[];const deadline=setTimeout(()=>{console.error('Timeout',errors);app.exit(1);},120000);app.on('web-contents-created',(_,wc)=>{wc.on('console-message',e=>{if(e.level==='error')errors.push(e.message);});wc.once('did-finish-load',async()=>{
 const run=f=>wc.executeJavaScript(`(${f.toString()})()`),wait=async(f,label)=>{for(let i=0;i<300;i++){if(await run(f))return;await new Promise(r=>setTimeout(r,50));}throw Error(label+': '+await run(()=>document.getElementById('editError').textContent));},click=id=>wc.executeJavaScript(`document.getElementById(${JSON.stringify(id)}).click()`),change=(id,value,type='input')=>wc.executeJavaScript(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event(${JSON.stringify(type)}));})()`),capture=async name=>{fs.mkdirSync(path.resolve(__dirname,'../work'),{recursive:true});await new Promise(r=>setTimeout(r,200));fs.writeFileSync(path.resolve(__dirname,'../work',name+'.png'),(await wc.capturePage()).toPNG());};
 try{
 await wait(()=>document.getElementById('scriptPicker').options.length===1&&document.querySelectorAll('.take-row').length===1,'init');const win=BrowserWindow.fromWebContents(wc);win.setSize(1200,800);
 await click('scriptNav');await change('scriptTitle','Intro Film');await change('script','Mein erstes gespeichertes Script.');await click('newProject');await change('projectName','Produktfilm');await click('createProject');await wait(()=>!document.getElementById('projectDialog').open,'project created');const lib=await run(()=>window.voice.library());assert.equal(lib.projects[0].name,'Produktfilm');assert.equal(lib.scripts[0].text,'Mein erstes gespeichertes Script.');
 await click('newScript');await wait(()=>document.getElementById('scriptPicker').options.length===2,'second script');await change('scriptTitle','Outro Film');await change('script','Vielen Dank fürs Zuhören.');await change('scriptPicker',lib.scripts[0].id,'change');await wait(()=>document.getElementById('script').value==='Mein erstes gespeichertes Script.','switch preserves text');assert.equal((await run(()=>window.voice.library())).scripts[1].text,'Vielen Dank fürs Zuhören.');await capture('studio-scripts');
 await run(()=>document.querySelector('.take-select').click());await wait(()=>!document.getElementById('libraryEdit').disabled,'take selected');await click('libraryDetails');await change('takeNameInput','Produktfilm · Intro');await click('takeFavorite');await change('takeProject',lib.projects[0].id,'change');await change('takeScript',lib.scripts[0].id,'change');await click('linkBrinkProject');await wait(()=>!document.getElementById('sendToBrink').disabled,'project linked');await click('sendToBrink');await wait(()=>document.getElementById('takeDetailsStatus').textContent.includes('übergeben'),'brink delivery');assert.equal(fs.readdirSync(path.join(project,'media/sounds')).length,1);await click('exportCine');await wait(()=>document.getElementById('takeDetailsStatus').textContent.includes('CINE-Projekt'),'cine delivery');assert.equal(JSON.parse(fs.readFileSync(cine)).format,'brink-videoeditor');await capture('studio-take-details');await click('saveTakeDetails');await wait(()=>!document.getElementById('takeDetailsDialog').open,'details saved');const named=(await run(()=>window.voice.list()))[0];assert.equal(named.favorite,true);assert.equal(named.scriptId,lib.scripts[0].id);await change('takeSearch','unbekannt');assert.equal(await run(()=>document.querySelectorAll('.take-row').length),0);await change('takeSearch','Produkt');assert.equal(await run(()=>document.querySelectorAll('.take-row').length),1);await click('favoriteFilter');assert.equal(await run(()=>document.querySelectorAll('.take-row').length),1);await click('favoriteFilter');await change('takeSearch','');
 await run(()=>document.querySelector('.take-rename').click());await run(()=>{const input=document.querySelector('.take-name-form input');input.value='Nicht speichern';input.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));});assert.equal(await run(()=>document.querySelector('.take-name-form')),null);assert.equal((await run(()=>window.voice.list()))[0].name,'Produktfilm · Intro');
 await run(()=>document.querySelector('.take-rename').click());await run(()=>{const form=document.querySelector('.take-name-form');form.querySelector('input').value='   ';form.requestSubmit();});assert.equal(await run(()=>document.querySelector('.take-name-error').hidden),false);
 await run(()=>{const input=document.querySelector('.take-name-form input');input.value='Produktfilm · Intro final';input.dispatchEvent(new Event('input'));input.focus();});await capture('studio-take-rename');wc.sendInputEvent({type:'keyDown',keyCode:'Return'});wc.sendInputEvent({type:'keyUp',keyCode:'Return'});await wait(()=>!document.querySelector('.take-name-form')&&document.querySelector('.take-select strong').textContent.includes('Intro final'),'inline rename saved');assert.equal(await run(()=>document.getElementById('previewName').textContent),'Produktfilm · Intro final');const renamed=(await run(()=>window.voice.list()))[0];assert.equal(renamed.favorite,true);assert.equal(renamed.scriptId,lib.scripts[0].id);assert.equal(renamed.projectId,lib.projects[0].id);
 await click('libraryEdit');await wait(()=>document.querySelectorAll('.cut-region').length===3&&!document.getElementById('applyCleanup').disabled,'analysis');await click('keepCut');assert.equal(await run(()=>document.querySelector('.cut-region').classList.contains('kept')),true);await click('undoEdit');assert.equal(await run(()=>document.querySelector('.cut-region').classList.contains('kept')),false);await click('redoEdit');assert.equal(await run(()=>document.querySelector('.cut-region').classList.contains('kept')),true);await click('undoEdit');
 await change('editZoom',4);await wait(()=>document.getElementById('editTimeline').clientWidth>document.getElementById('editViewport').clientWidth*3.9,'zoom');await run(()=>document.getElementById('editViewport').scrollLeft=document.getElementById('editViewport').clientWidth);await new Promise(r=>setTimeout(r,150));assert.ok(await run(()=>document.getElementById('editViewport').scrollLeft>0));await change('editZoom',1);await click('selectionMode');
 async function select(a,b){const r=await run(()=>{const r=document.getElementById('editTimeline').getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};});const y=Math.round(r.y+r.height/2),x=Math.round(r.x+r.width*a);wc.sendInputEvent({type:'mouseDown',x,y,button:'left',clickCount:1});wc.sendInputEvent({type:'mouseMove',x:Math.round(r.x+r.width*b),y,button:'left'});wc.sendInputEvent({type:'mouseUp',x:Math.round(r.x+r.width*b),y,button:'left',clickCount:1});await new Promise(r=>setTimeout(r,50));}
 await select(.18,.23);await click('deleteSelection');assert.equal(await run(()=>document.querySelectorAll('.cut-region').length),4);await click('undoEdit');assert.equal(await run(()=>document.querySelectorAll('.cut-region').length),3);await click('redoEdit');assert.equal(await run(()=>document.querySelectorAll('.cut-region').length),4);await select(.05,.95);await click('trimSelection');assert.equal(await run(()=>document.querySelectorAll('.cut-region').length),6);await capture('studio-cuts');await click('undoEdit');await click('undoEdit');await click('selectionMode');
 await click('effectsTab');await change('effectPreset','podcast','change');assert.equal(await run(()=>document.getElementById('fx-compressor').checked),true);await change('fx-isolation',55);await change('presetName','Meine Stimme');await click('savePreset');assert.equal(await run(()=>document.getElementById('effectPreset').selectedOptions[0].textContent),'Meine Stimme');await capture('studio-effects');
 await click('previewEffects');await wait(()=>document.getElementById('editSummary').dataset.state==='success'&&!document.getElementById('editResult').disabled,'effects preview');assert.match(await run(()=>document.getElementById('editAudio').src),/^voice:\/\/preview\//);assert.equal((await run(()=>window.voice.list())).length,1);await wait(()=>!document.getElementById('editPlay').disabled,'preview metadata');await click('editPlay');await wait(()=>document.getElementById('editAudio').currentTime>.1,'processed playback');await click('editOriginal');assert.match(await run(()=>document.getElementById('editAudio').src),/^voice:\/\/take\//);await click('editResult');assert.match(await run(()=>document.getElementById('editAudio').src),/^voice:\/\/preview\//);
 await change('fx-bass',4);assert.equal(await run(()=>document.getElementById('editResult').disabled),true);await click('applyCleanup');await wait(()=>!document.getElementById('exportCleanup').hidden,'effects saved');assert.equal((await run(()=>window.voice.list())).length,2);assert.deepEqual(fs.readFileSync(file),original);await capture('studio-effects-result');await click('closeEdit');
 await click('importAudio');await wait(()=>document.querySelectorAll('.take-row').length===3&&!document.getElementById('jobDialog').open,'audio imported');assert.equal((await run(()=>window.voice.list())).filter(t=>t.kind==='imported').length,1);
 // Restore the source's saved edit draft and user preset after a full renderer reload.
 wc.reload();await new Promise(r=>wc.once('did-finish-load',r));await wait(()=>document.getElementById('scriptPicker').options.length===2&&document.querySelectorAll('.take-row').length===3,'reload library');assert.equal((await run(()=>window.voice.list())).find(t=>t.id===id).name,'Produktfilm · Intro final');await wc.executeJavaScript(`document.querySelector('[data-id="${id}"] .take-select').click()`);await wait(()=>!document.getElementById('libraryEdit').disabled,'source selected');await click('libraryEdit');await wait(()=>!document.getElementById('previewEffects').disabled,'draft restored');await click('effectsTab');assert.equal(await run(()=>Number(document.getElementById('fx-bass').value)),4);assert.ok(await run(()=>[...document.getElementById('effectPreset').options].some(o=>o.textContent==='Meine Stimme')));
 win.setSize(1060,720);await new Promise(r=>setTimeout(r,150));assert.ok(await run(()=>{const d=document.getElementById('editDialog'),b=document.getElementById('applyCleanup').getBoundingClientRect();return d.scrollHeight<=d.clientHeight+1&&b.bottom<innerHeight;}));await capture('studio-effects-small');await run(()=>{document.getElementById('theme').value='light';document.getElementById('theme').dispatchEvent(new Event('change'));});await capture('studio-effects-light');await click('closeEdit');assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,checks:['inline rename save/cancel/empty validation and restart persistence','multiple scripts and switching','project creation','name favorite and associations','search and favorite filter','BRINK handoff','CINE project export','keep pause','undo and redo','zoom and scroll','real manual selection cut and trim','effects preset and own preset','RNNoise preview playback','original/result comparison','stale preview invalidation','effect save preserves original','audio import','reload persists edits scripts and presets','small/light editor'],artifacts:path.resolve(__dirname,'../work')}));clearTimeout(deadline);app.exit(0);
 }catch(e){console.error(e,errors);await capture('studio-failure');clearTimeout(deadline);app.exit(1);}
 });});require('../electron/main.cjs');
