const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process'),{randomUUID}=require('node:crypto');
const {atomic}=require('./library.cjs'),{wavInfo}=require('./edits.cjs');
const LANGUAGES=new Set(['auto','de','en','fr','es','it','pt','nl','pl','tr','ru','uk','ja','zh']);
function language(value){if(!LANGUAGES.has(value))throw Error('Bitte eine unterstützte Sprache auswählen.');return value;}
function transcriptText(value){if(typeof value!=='string'||value.length>2*1024*1024)throw Error('Der Transkript-Text ist ungültig oder zu lang.');return value;}
function parseResult(value,duration){if(!Array.isArray(value?.transcription))throw Error('Whisper hat kein lesbares Ergebnis geliefert.');const segments=value.transcription.map(s=>{const start=Number(s.offsets?.from)/1000,end=Number(s.offsets?.to)/1000;if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end<start)throw Error('Ungültige Zeitangaben im Transkript.');return {start:Math.min(duration,start),end:Math.min(duration,end),text:transcriptText(s.text).trim()};}).filter(s=>s.text);return {text:transcriptText(segments.map(s=>s.text).join('\n')),segments,language:typeof value.result?.language==='string'?value.result.language:'auto'};}
class Transcriptions{
 constructor({store,root,cache,runtime}){Object.assign(this,{store,root,cache,runtime});this.active=null;this.jobs=new Map();this.queue=Promise.resolve();}
 async init(){await fs.mkdir(this.root,{recursive:true});await fs.rm(this.cache,{recursive:true,force:true});await fs.mkdir(this.cache,{recursive:true});}
 file(id){this.store.file(id);return path.join(this.root,id+'.json');}
 async get(id){await fs.access(this.store.file(id));try{return JSON.parse(await fs.readFile(this.file(id),'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw e;}}
 async available(){try{if(process.platform!=='darwin'||process.arch!=='arm64')throw Error();await fs.access(path.join(this.runtime,'bin/whisper-cli'),fs.constants.X_OK);const model=await fs.stat(path.join(this.runtime,'models/ggml-base.bin'));if(model.size!==147951465)throw Error();return {available:true,model:'Whisper Base',local:true};}catch{return {available:false,model:'Whisper Base',local:true,message:'Die lokale Whisper-Engine oder das Modell fehlt. Bitte die vollständige VOICE-App für Apple Silicon verwenden.'};}}
 status(id){const j=this.jobs.get(id);if(!j)throw Error('Transkriptionsauftrag nicht gefunden.');return {id:j.id,state:j.state,progress:j.progress,label:j.label,error:j.error,result:j.state==='done'?j.result:undefined};}
 cancel(id){const j=this.jobs.get(id);if(j?.state==='running'&&!j.committing){j.cancelled=true;j.label='Wird abgebrochen …';j.child?.kill('SIGTERM');if(j.child){const child=j.child;const timer=setTimeout(()=>child.kill('SIGKILL'),1500);timer.unref();child.once('close',()=>clearTimeout(timer));}}return true;}
 check(job){if(job.cancelled)throw Error('Transkription abgebrochen.');}
 async command(job,binary,args,progress){this.check(job);await new Promise((resolve,reject)=>{let stderr='';const child=spawn(binary,args,{stdio:['ignore','ignore','pipe'],windowsHide:true});job.child=child;child.stderr.on('data',chunk=>{stderr=(stderr+chunk).slice(-8000);if(progress)for(const match of stderr.matchAll(/progress\s*=\s*(\d+)%/g))job.progress=Math.max(job.progress,.12+.82*Math.min(100,Number(match[1]))/100);});child.once('error',reject);child.once('close',code=>{job.child=null;if(code===0)resolve();else reject(Error(job.cancelled?'Transkription abgebrochen.':`Audio konnte nicht transkribiert werden. ${stderr.slice(-500)}`));});});this.check(job);}
 async start(id,spokenLanguage){language(spokenLanguage);this.store.file(id);if(this.active||this.store.active)throw Error('Bitte die laufende Aufnahme oder Verarbeitung zuerst beenden.');const job={id:randomUUID(),takeId:id,state:'running',progress:0,label:'Whisper wird vorbereitet …',child:null};this.active=job;this.jobs.set(job.id,job);try{const available=await this.available();if(!available.available)throw Error(available.message);const info=await wavInfo(this.store.file(id));if(info.duration<.2||info.duration>7200)throw Error('Bitte einen Take zwischen 0,2 Sekunden und 2 Stunden auswählen.');void this.run(job,spokenLanguage,info);while(this.jobs.size>20)this.jobs.delete(this.jobs.keys().next().value);return {jobId:job.id};}catch(e){this.active=null;this.jobs.delete(job.id);throw e;}}
 async run(job,spokenLanguage,info){let temp;try{temp=await fs.mkdtemp(path.join(this.cache,'take-'));const wav=path.join(temp,'input.wav'),output=path.join(temp,'transcript');job.label='Audio wird vorbereitet …';job.progress=.03;
 const ffmpeg=require('ffmpeg-static').replace('app.asar'+path.sep,'app.asar.unpacked'+path.sep);await this.command(job,ffmpeg,['-nostdin','-hide_banner','-loglevel','error','-y','-i',this.store.file(job.takeId),'-vn','-ac','1','-ar','16000','-c:a','pcm_s16le','-bitexact',wav]);
 // Avoid invented speech from an entirely silent capture; inspect PCM without loading a whole take.
 const input=await fs.open(wav,'r');let signal=false;try{const buf=Buffer.alloc(65536);let offset=44;while(!signal){this.check(job);const {bytesRead}=await input.read(buf,0,buf.length,offset);if(!bytesRead)break;for(let i=0;i+1<bytesRead;i+=2)if(Math.abs(buf.readInt16LE(i))>8){signal=true;break;}offset+=bytesRead;}}finally{await input.close();}
 let result={text:'',segments:[],language:spokenLanguage};
 if(signal){job.label='Whisper wandelt Sprache in Text um …';job.progress=.12;const args=['-m',path.join(this.runtime,'models/ggml-base.bin'),'-f',wav,'-l',spokenLanguage,'-oj','-of',output,'-pp','-t',String(Math.min(6,os.availableParallelism()))];try{await this.command(job,path.join(this.runtime,'bin/whisper-cli'),args,true);}catch(e){this.check(job);job.label='Transkription wird auf dem Prozessor fortgesetzt …';await this.command(job,path.join(this.runtime,'bin/whisper-cli'),[...args,'-ng'],true);}const stat=await fs.stat(output+'.json');if(stat.size>8*1024*1024)throw Error('Das Transkript ist zu groß. Bitte den Take aufteilen.');result=parseResult(JSON.parse(await fs.readFile(output+'.json','utf8')),info.duration);}
 this.check(job);const previous=await this.get(job.takeId);const document={...result,id:job.takeId,model:'base',engine:'whisper.cpp',created:previous?.created||Date.now(),updated:Date.now(),duration:info.duration};job.committing=true;job.label='Transkript wird gespeichert …';await atomic(this.file(job.takeId),document);job.result=document;job.progress=1;job.label=document.text?'Transkript bereit':'Keine Sprache erkannt';job.state='done';
 }catch(e){job.state=job.cancelled?'cancelled':'error';job.error=e.message;job.label=job.cancelled?'Abgebrochen':'Transkription nicht abgeschlossen';}finally{if(temp)await fs.rm(temp,{recursive:true,force:true}).catch(()=>{});if(this.active===job)this.active=null;}}
 async save(id,text){transcriptText(text);if(this.active?.takeId===id)throw Error('Bitte die Transkription zuerst beenden.');const task=this.queue.then(async()=>{const doc=await this.get(id);if(!doc)throw Error('Für diesen Take gibt es noch kein Transkript.');const next={...doc,text,updated:Date.now(),edited:text!==doc.text||!!doc.edited};await atomic(this.file(id),next);return next;});this.queue=task.catch(()=>{});return task;}
 async remove(id){await fs.unlink(this.file(id)).catch(e=>{if(e.code!=='ENOENT')throw e;});}
}
module.exports={Transcriptions,language,transcriptText,parseResult};
