import {EditHistory,defaultEffects,presets,mergeCuts,outputToSource,sourceToOutput} from './edit-model.mjs';
export function createEditor({api,$,icons,timeLabel,onSaved,takeName,drawWave}){
 let source=null,history=null,automatic=[],selected=0,selection=null,working=false,jobId=null,generation=0,preview=null,savedResult=null,viewPeaks=[],viewStart=0,viewEnd=0,waveGeneration=0,waveTimer,zoom=1,drag=null,group=null,auditionEnd=null;
 const player=$('editAudio');player.volume=.8;
 const clone=v=>structuredClone(v),state=()=>history?.value;
 const seconds=v=>v<.1?'unter 0,1 s':`${v.toLocaleString('de-DE',{minimumFractionDigits:1,maximumFractionDigits:1})} s`;
 const clock=v=>{const n=Math.round(v*10);return `${String(Math.floor(n/600)).padStart(2,'0')}:${String(Math.floor(n/10)%60).padStart(2,'0')},${n%10}`;};
 const activeCuts=()=>mergeCuts((state()?.regions||[]).filter(r=>r.enabled).map(r=>[r.start,r.end]),source?.duration||0);
 const effectChanged=()=>Object.keys(defaultEffects).some(k=>state()?.effects[k]!==defaultEffects[k]);
 const removed=()=>activeCuts().reduce((n,[a,b])=>n+b-a,0);
 function status(kind,title,detail=''){$('editSummary').dataset.state=kind;$('editStatusTitle').textContent=title;$('editStatusDetail').textContent=detail;$('editStatusIcon').dataset.icon={busy:'action-refresh',ready:'action-info',modified:'action-edit',success:'action-check',error:'status-warning',empty:'action-info'}[kind];icons($('editSummary'));}
 function error(e){status('error','Bitte prüfen',e.message||String(e));$('editError').textContent=e.message||String(e);$('editError').hidden=false;}
 function playingResult(){return player.getAttribute('src')?.startsWith('voice://preview/') || (savedResult && player.getAttribute('src')===`voice://take/${savedResult.id}`);}
 function sourcePosition(){return playingResult()?outputToSource(player.currentTime,activeCuts(),source.duration):player.currentTime;}
 function setAudio(kind='original',position=0){player.pause();auditionEnd=null;let url=`voice://take/${source.id}`;if(kind==='result'){if(preview)url=`voice://preview/${preview.id}`;else if(savedResult)url=`voice://take/${savedResult.id}`;else return;}
  player.src=url;player.load();$('editListenLabel').textContent=kind==='original'?'Original anhören':'Ergebnis anhören';$('editListenLabel').dataset.result=String(kind!=='original');
  if(position>0){const expected=url;player.addEventListener('loadedmetadata',()=>{if(player.getAttribute('src')===expected)player.currentTime=Math.min(player.duration,position);},{once:true});}
 }
 function invalidate(){const position=source?sourcePosition():0;player.pause();auditionEnd=null;if(preview){void api.removePreview(preview.id);preview=null;}if(savedResult||playingResult())setAudio('original',position);savedResult=null;$('exportCleanup').hidden=true;}
 function persist(){try{localStorage.setItem('voice-edit-'+source.id,JSON.stringify({duration:source.duration,value:state()}));$('editDraftState').textContent='Bearbeitungsentwurf gespeichert';}catch{$('editDraftState').textContent='Entwurf konnte nicht gespeichert werden';}}
 function summary(){if(!history)return;const count=state().regions.filter(r=>r.enabled).length,changed=history.past.length>0;status(changed?'modified':count?'ready':'empty',changed?'Bearbeitung angepasst':count?`${count} Pausen erkannt`:'Keine längeren Pausen gefunden',`${seconds(removed())} entfernt · Ergebnis ${seconds(source.duration-removed())}${effectChanged()?' · Klangeffekte aktiv':''}`);}
 function changed(rebuild=true){invalidate();$('editError').hidden=true;persist();summary();if(rebuild)renderRegions();sync();}
 function commit(fn,rebuild=true){if(working||!history)return;const value=clone(state());fn(value);if(history.commit(value))changed(rebuild);}
 function beginGroup(){if(!group)group=clone(state());}
 function groupChange(fn,rebuild=false){if(working)return;fn(history.value);changed(rebuild);}
 function endGroup(){if(!group)return;const value=clone(state());history.value=group;group=null;history.commit(value);persist();sync();}
 function sync(){
  const st=state(),region=st?.regions[selected],cuts=st?activeCuts():[],remaining=source?source.duration-removed():0,modified=cuts.length>0||effectChanged();
  $('undoEdit').disabled=working||!history?.past.length;$('redoEdit').disabled=working||!history?.future.length;
  for(const id of ['silenceThreshold','silenceMinimum','silenceKeep','detectSilence','selectionMode','editZoom','resetCuts','resetEffects','effectPreset','savePreset','presetName'])$(id).disabled=working||!st;
  for(const input of $('effectControls').querySelectorAll('input'))input.disabled=working;
  $('cutRegions').dataset.working=String(working);$('applyCleanup').disabled=working||!modified||remaining<.01;$('previewEffects').disabled=working||remaining<.01;
  $('applyCleanup').hidden=!!savedResult;$('exportCleanup').hidden=!savedResult;$('editResult').disabled=working||(!preview&&!savedResult);$('editOriginal').disabled=working;
  $('cancelEditJob').hidden=!working||!jobId;$('editProgress').hidden=!working;$('closeEdit').disabled=working;
  $('cutControls').hidden=!region;
  for(const id of ['cutSelection','cutLess','cutMore','keepCut','listenCut','previousCut','nextCut'])$(id).disabled=working||!region;
  $('previousCut').disabled ||= selected===0;$('nextCut').disabled ||= selected===(st?.regions.length||0)-1;
  if(region){$('cutSelection').value=String(selected);$('cutDuration').textContent=`${seconds(region.end-region.start)} ${region.enabled?'entfernen':'behalten'}`;$('cutRange').textContent=`${clock(region.start)} – ${clock(region.end)}`;$('keepCut').textContent=region.enabled?'Bereich behalten':'Doch entfernen';}
  const hasSelection=selection&&selection[1]-selection[0]>=.01;
  for(const id of ['deleteSelection','trimSelection','clearSelection'])$(id).disabled=working||!hasSelection;
  $('selectionLabel').textContent=hasSelection?`${clock(selection[0])} – ${clock(selection[1])} · ${seconds(selection[1]-selection[0])}`:'Zum Schneiden einen Bereich markieren.';
  $('manualSelection').hidden=!hasSelection;if(hasSelection){$('manualSelection').style.left=selection[0]/source.duration*100+'%';$('manualSelection').style.width=(selection[1]-selection[0])/source.duration*100+'%';}
  for(const el of $('cutRegions').children){const r=st.regions[Number(el.dataset.index)];el.style.left=r.start/source.duration*100+'%';el.style.width=(r.end-r.start)/source.duration*100+'%';el.dataset.start=r.start;el.dataset.end=r.end;el.classList.toggle('selected',Number(el.dataset.index)===selected);el.classList.toggle('kept',!r.enabled);for(const b of el.querySelectorAll('button')){b.disabled=working;if(b.dataset.part!=='move'){const v=b.dataset.part==='start'?r.start:r.end;b.setAttribute('aria-valuenow',v.toFixed(1));b.setAttribute('aria-valuetext',clock(v));b.setAttribute('aria-valuemin','0');b.setAttribute('aria-valuemax',String(source.duration));}}}
  for(const [key,input]of effectInputs){input.type==='checkbox'?input.checked=!!st?.effects[key]:input.value=st?.effects[key]??defaultEffects[key];const out=$('fxValue-'+key);if(out)out.textContent=formatEffect(key,Number(input.value));}
 }
 function cutMove(index,part,delta,base){const r=history.value.regions[index],original=base.regions[index],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let a=original.start,b=original.end;
  if(part==='start')a=clamp(a+delta,0,b-.01);else if(part==='end')b=clamp(b+delta,a+.01,source.duration);else{const shift=clamp(delta,-a,source.duration-b);a+=shift;b+=shift;}
  r.start=Math.round(a*source.rate)/source.rate;r.end=Math.round(b*source.rate)/source.rate;
 }
 function renderRegions(){
  $('cutRegions').replaceChildren();$('cutSelection').replaceChildren();const regions=state()?.regions||[];selected=Math.max(0,Math.min(selected,regions.length-1));
  regions.forEach((r,index)=>{const label=`${r.kind==='manual'?'Schnitt':r.kind==='trim'?'Rand':'Pause'} ${index+1}`;$('cutSelection').add(new Option(label+(r.enabled?'':' · behalten'),String(index)));const region=document.createElement('div');region.className='cut-region';region.dataset.index=index;
   for(const part of ['move','start','end']){const b=document.createElement('button');b.type='button';b.className=part==='move'?'cut-move':'cut-handle';b.dataset.part=part;b.setAttribute('aria-label',`${label}: ${part==='move'?'verschieben':part==='start'?'Beginn':'Ende'}`);if(part==='move')b.textContent=String(index+1);else{b.setAttribute('role','slider');b.setAttribute('aria-orientation','horizontal');}
    b.onfocus=()=>{selected=index;sync();};b.onpointerdown=e=>{if(working||$('selectionMode').checked||e.button!==0)return;e.preventDefault();e.stopPropagation();selected=index;b.focus();beginGroup();player.pause();drag={id:e.pointerId,x:e.clientX,index,part,base:clone(state()),width:$('editTimeline').clientWidth};b.setPointerCapture(e.pointerId);};
    b.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;groupChange(()=>cutMove(index,part,(e.clientX-drag.x)/drag.width*source.duration,drag.base));};
    const end=e=>{if(drag?.id===e.pointerId){drag=null;endGroup();if(b.hasPointerCapture(e.pointerId))b.releasePointerCapture(e.pointerId);}};b.onpointerup=end;b.onlostpointercapture=end;b.onpointercancel=e=>{if(drag){history.value=drag.base;changed(false);}end(e);};
    b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key)||working)return;e.preventDefault();const base=clone(state());beginGroup();groupChange(()=>cutMove(index,part,(e.key==='ArrowLeft'?-1:1)*(e.shiftKey ? .1 : .01),base));endGroup();};region.append(b);
   }$('cutRegions').append(region);
  });sync();
 }
 async function loadWave(){if(!source||!$('editDialog').open)return;const viewport=$('editViewport'),width=Math.max(1,viewport.clientWidth),total=width*zoom;viewStart=viewport.scrollLeft/total*source.duration;viewEnd=Math.min(source.duration,viewStart+source.duration/zoom);const request=++waveGeneration;try{const data=await api.waveform(source.id,{start:viewStart,end:viewEnd,bins:Math.ceil(width*2)});if(request===waveGeneration)viewPeaks=data.peaks;}catch(e){error(e);}}
 function layoutWave(){const width=$('editViewport').clientWidth;$('editTimeline').style.width=width*zoom+'px';$('editWave').style.width=width+'px';$('editZoomValue').textContent=zoom+'×';void loadWave();}
 new ResizeObserver(()=>{if($('editDialog').open)layoutWave();}).observe($('editViewport'));
 $('editViewport').onscroll=()=>{clearTimeout(waveTimer);waveTimer=setTimeout(loadWave,60);};$('editZoom').oninput=()=>{zoom=Number($('editZoom').value);layoutWave();};
 $('selectionMode').onchange=()=>{$('cutRegions').classList.toggle('select-mode',$('selectionMode').checked);};
 let selectionDrag=null;
 $('editTimeline').onclick=e=>{if(working||$('selectionMode').checked||e.target.closest('.cut-region'))return;const r=$('editTimeline').getBoundingClientRect(),position=Math.max(0,Math.min(source.duration,(e.clientX-r.left)/r.width*source.duration));auditionEnd=null;if(player.readyState)player.currentTime=playingResult()?sourceToOutput(position,activeCuts()):position;};
 $('editTimeline').onpointerdown=e=>{if(working||!$('selectionMode').checked||e.button!==0)return;const rect=$('editTimeline').getBoundingClientRect(),position=Math.max(0,Math.min(source.duration,(e.clientX-rect.left)/rect.width*source.duration));selectionDrag={id:e.pointerId,start:position};selection=[position,position];player.pause();$('editTimeline').setPointerCapture(e.pointerId);sync();};
 $('editTimeline').onpointermove=e=>{if(!selectionDrag||selectionDrag.id!==e.pointerId)return;const rect=$('editTimeline').getBoundingClientRect(),end=Math.max(0,Math.min(source.duration,(e.clientX-rect.left)/rect.width*source.duration));selection=[Math.min(selectionDrag.start,end),Math.max(selectionDrag.start,end)];sync();};
 $('editTimeline').onpointerup=e=>{if(selectionDrag?.id===e.pointerId){selectionDrag=null;$('editTimeline').releasePointerCapture(e.pointerId);}};
 $('deleteSelection').onclick=()=>{if(!selection)return;commit(s=>s.regions.push({id:crypto.randomUUID(),kind:'manual',start:selection[0],end:selection[1],enabled:true}));selected=state().regions.length-1;selection=null;renderRegions();};
 $('trimSelection').onclick=()=>{if(!selection)return;commit(s=>{s.regions=s.regions.filter(r=>r.kind!=='trim');if(selection[0]>.0001)s.regions.push({id:crypto.randomUUID(),kind:'trim',start:0,end:selection[0],enabled:true});if(selection[1]<source.duration-.0001)s.regions.push({id:crypto.randomUUID(),kind:'trim',start:selection[1],end:source.duration,enabled:true});});selection=null;sync();};$('clearSelection').onclick=()=>{selection=null;sync();};
 $('cutSelection').onchange=()=>{selected=Number($('cutSelection').value);sync();};$('previousCut').onclick=()=>{selected--;sync();};$('nextCut').onclick=()=>{selected++;sync();};
 $('keepCut').onclick=()=>commit(s=>{s.regions[selected].enabled=!s.regions[selected].enabled;});
 function resize(expand){if(!state()?.regions[selected])return;beginGroup();const r=state().regions[selected],amount=expand ? .05 : Math.min(.05,Math.max(0,(r.end-r.start-.01)/2));let base=clone(state());groupChange(()=>cutMove(selected,'start',expand?-amount:amount,base));base=clone(state());groupChange(()=>cutMove(selected,'end',expand?amount:-amount,base));endGroup();}
 $('cutLess').onclick=()=>resize(false);$('cutMore').onclick=()=>resize(true);
 $('resetCuts').onclick=()=>commit(s=>{s.regions=clone(automatic);});
 function undo(){if(!working&&history?.undo())changed();}function redo(){if(!working&&history?.redo())changed();}$('undoEdit').onclick=undo;$('redoEdit').onclick=redo;
 $('editDialog').addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();e.shiftKey?redo():undo();}});
 async function detect(initial=false){if(working)return;const epoch=++generation;invalidate();working=true;sync();status('busy','Pausen werden gesucht …');try{const plan=await api.analyzeSilence(source.id,{threshold:Number($('silenceThreshold').value),minimum:Number($('silenceMinimum').value),keep:Number($('silenceKeep').value)});if(epoch!==generation)return;automatic=plan.cuts.map(([start,end])=>({id:crypto.randomUUID(),kind:'pause',start,end,enabled:true}));if(initial){history=new EditHistory({regions:clone(automatic),effects:{...defaultEffects}});try{const draft=JSON.parse(localStorage.getItem('voice-edit-'+source.id));if(draft?.duration===source.duration&&Array.isArray(draft.value?.regions)&&draft.value.regions.length<20000){const r=draft.value.regions;if(r.every(v=>Number.isFinite(v.start)&&Number.isFinite(v.end)&&v.start>=0&&v.end>v.start&&v.end<=source.duration))history=new EditHistory({regions:r,effects:{...defaultEffects,...draft.value.effects}});}}catch{}}else{const value=clone(state());value.regions=[...value.regions.filter(r=>r.kind!=='pause'),...clone(automatic)];history.commit(value);}renderRegions();summary();persist();}catch(e){error(e);}finally{working=false;sync();}}
 $('detectSilence').onclick=()=>void detect();
 for(const id of ['silenceThreshold','silenceMinimum','silenceKeep'])$(id).onchange=()=>void detect();
 function tab(effects){$('cutPane').hidden=effects;$('effectsPane').hidden=!effects;$('cutTab').setAttribute('aria-selected',String(!effects));$('effectsTab').setAttribute('aria-selected',String(effects));if(!effects)layoutWave();}$('cutTab').onclick=()=>tab(false);$('effectsTab').onclick=()=>tab(true);
 const controlGroups=[
  ['Stimmisolation','Lokale, sprachoptimierte KI-Rauschunterdrückung. Überlagerte Stimmen oder Musik lassen sich damit nicht zuverlässig trennen.',[['isolation','Stärke',0,100,5,'%'],['highpass','Rumpelfilter',0,200,10,'Hz']]],
  ['Gate & Dynamik','Stille beruhigen und Lautstärkeschwankungen sanft ausgleichen.',[['gate','Gate',0,100,5,'%'],['gateThreshold','Gate-Schwelle',-70,-20,1,'dB'],['dynamics','Auto-Level',0,100,5,'%']]],
  ['Kompressor','Laute Stellen einfangen und die Stimme dichter machen.',[['compressor','Kompressor aktiv'],['threshold','Schwelle',-48,-3,1,'dB'],['ratio','Verhältnis',1,12,.5,':1'],['attack','Attack',1,100,1,'ms'],['release','Release',20,1000,10,'ms'],['makeup','Aufholverstärkung',0,18,.5,'dB']]],
  ['Equalizer & Bass','Wärme, Verständlichkeit und Brillanz gezielt formen.',[['bass','Bass · 120 Hz',-12,12,.5,'dB'],['lowMid','Wärme · 300 Hz',-12,12,.5,'dB'],['mid','Mitten · 1 kHz',-12,12,.5,'dB'],['presence','Präsenz · 3,5 kHz',-12,12,.5,'dB'],['air','Brillanz · 8 kHz',-12,12,.5,'dB']]],
  ['De-Esser','Scharfe S- und Zischlaute abschwächen.',[['deesser','Stärke',0,100,5,'%']]],
  ['Lautstärke & Ausgang','Ziel-Lautheit und Schutz vor Übersteuerung.',[['normalize','Lautstärke angleichen'],['target','Ziel-Lautheit',-24,-12,1,'LUFS'],['output','Ausgangspegel',-18,12,.5,'dB'],['limiter','Limiter · −1 dB']]]
 ];
 const effectInputs=new Map(),units=new Map();function formatEffect(key,v){if(key==='highpass'&&v===0)return 'Aus';return `${v.toLocaleString('de-DE',{maximumFractionDigits:1})} ${units.get(key)||''}`;}
 for(const [title,description,controls]of controlGroups){const card=document.createElement('section');card.className='effect-card';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=description;card.append(h,p);for(const [key,label,min,max,step,unit]of controls){const row=document.createElement('label');row.className='effect-control';const name=document.createElement('span');name.textContent=label;const input=document.createElement('input');input.id='fx-'+key;input.type=min===undefined?'checkbox':'range';if(min!==undefined){input.min=min;input.max=max;input.step=step;units.set(key,unit);const out=document.createElement('output');out.id='fxValue-'+key;row.append(name,out,input);}else row.append(input,name);effectInputs.set(key,input);input.onpointerdown=()=>{if(!working)beginGroup();};input.oninput=()=>{const value=input.type==='checkbox'?input.checked:Number(input.value);if(group)groupChange(s=>{history.value.effects[key]=value;});else commit(s=>{s.effects[key]=value;},false);$('effectPreset').value='custom';};input.onchange=()=>endGroup();input.onpointerup=()=>endGroup();input.onpointercancel=()=>endGroup();card.append(row);} $('effectControls').append(card);}
 let userPresets={};try{userPresets=JSON.parse(localStorage.getItem('voice-effect-presets')||'{}');}catch{}
 function presetList(){const select=$('effectPreset');select.replaceChildren();for(const [key,p]of Object.entries(presets))select.add(new Option(p.label,key));for(const [key,p]of Object.entries(userPresets))select.add(new Option(p.label,key));select.add(new Option('Eigene Einstellung','custom'));}presetList();
 $('effectPreset').onchange=()=>{const p=presets[$('effectPreset').value]||userPresets[$('effectPreset').value];if(p)commit(s=>{s.effects={...defaultEffects,...p.values};},false);};$('resetEffects').onclick=()=>{commit(s=>{s.effects={...defaultEffects};},false);$('effectPreset').value='original';};
 $('savePreset').onclick=()=>{const name=$('presetName').value.trim();if(!name){$('presetName').focus();return;}const key='user-'+crypto.randomUUID();userPresets[key]={label:name,values:clone(state().effects)};try{localStorage.setItem('voice-effect-presets',JSON.stringify(userPresets));presetList();$('effectPreset').value=key;$('presetName').value='';status('success','Klangvorlage gespeichert',name);}catch(e){error(e);}};
 async function waitJob(id){jobId=id;sync();while(true){const result=await api.jobStatus(id);$('editProgress').value=result.progress;status('busy',result.label||'Audio wird verarbeitet',`${Math.round(result.progress*100)} % · Verarbeitung auf deinem Gerät`);if(result.state==='done')return result.result;if(result.state==='error'||result.state==='cancelled')throw Error(result.error||'Abgebrochen.');await new Promise(r=>setTimeout(r,100));}}
 async function process(previewOnly){if(working||!history)return;working=true;player.pause();sync();status('busy','Audio wird vorbereitet …');$('editError').hidden=true;try{const {jobId:id}=await api.renderAudio({id:source.id,cuts:activeCuts(),effects:state().effects,preview:previewOnly});const result=await waitJob(id);if(preview)await api.removePreview(preview.id);preview=null;if(previewOnly){preview=result;savedResult=null;}else{savedResult=result;await onSaved(result.id);}setAudio('result');status('success',previewOnly?'Vorschau bereit':'Voice-over bereit',previewOnly?'Vergleiche Original und Ergebnis.':'Als neuer Take gespeichert. Dein Original bleibt erhalten.');}catch(e){error(e);}finally{working=false;jobId=null;sync();}}
 $('previewEffects').onclick=()=>process(true);$('applyCleanup').onclick=()=>process(false);$('cancelEditJob').onclick=()=>{if(jobId)void api.cancelJob(jobId);};
 $('editOriginal').onclick=()=>{const position=sourcePosition();setAudio('original',position);};$('editResult').onclick=()=>{const position=sourcePosition();setAudio('result',sourceToOutput(position,activeCuts()));};
 $('exportCleanup').onclick=async()=>{try{if(savedResult&&await api.export(savedResult.id))status('success','WAV exportiert','Dein Voice-over ist gespeichert.');}catch(e){error(e);}};
 $('editPlay').onclick=async()=>{try{auditionEnd=null;if(player.paused)await player.play();else player.pause();}catch(e){error(e);}};
 $('editSeek').oninput=()=>{auditionEnd=null;if(Number.isFinite(player.duration))player.currentTime=Number($('editSeek').value)/1000*player.duration;};
 for(const event of ['loadedmetadata','timeupdate','play','pause','ended','emptied'])player.addEventListener(event,()=>{if(auditionEnd!==null&&player.currentTime>=auditionEnd){auditionEnd=null;player.pause();}const duration=Number.isFinite(player.duration)?player.duration:0;$('editPlay').disabled=!duration;$('editSeek').disabled=!duration;$('editPlay').textContent=player.paused?'Abspielen':'Pause';$('editSeek').value=duration?player.currentTime/duration*1000:0;$('editPosition').textContent=`${timeLabel(player.currentTime)} / ${timeLabel(duration)}`;});
 player.addEventListener('error',()=>{if($('editDialog').open)error(Error('Die Audio-Vorschau konnte nicht geladen werden.'));});
 $('listenCut').onclick=async()=>{if(working||!state()?.regions[selected])return;const epoch=generation,r=state().regions[selected];try{if(playingResult()||player.readyState<1){setAudio('original');await new Promise((resolve,reject)=>{const timer=setTimeout(()=>finish(Error('Vorschau nicht verfügbar.')),4000),loaded=()=>finish(),failed=()=>finish(Error('Vorschau nicht verfügbar.'));function finish(e){clearTimeout(timer);player.removeEventListener('loadedmetadata',loaded);player.removeEventListener('error',failed);e?reject(e):resolve();}player.addEventListener('loadedmetadata',loaded);player.addEventListener('error',failed);});}if(epoch!==generation||!$('editDialog').open)return;player.currentTime=Math.max(0,r.start-.4);auditionEnd=Math.min(source.duration,r.end+.4);await player.play();}catch(e){error(e);}};
 function stop(){generation++;player.pause();auditionEnd=null;drag=null;group=null;if(preview){void api.removePreview(preview.id);preview=null;}}$('closeEdit').onclick=()=>{if(!working){stop();$('editDialog').close();}};$('editDialog').addEventListener('cancel',e=>{if(working)e.preventDefault();else stop();});$('editDialog').addEventListener('close',stop);
 return {async open(take){source=take;generation++;selected=0;selection=null;preview=null;savedResult=null;history=new EditHistory({regions:[],effects:{...defaultEffects}});working=false;zoom=1;$('editZoom').value=1;$('editViewport').scrollLeft=0;$('selectionMode').checked=false;$('cutRegions').classList.remove('select-mode');$('editTakeName').textContent=takeName(take);$('editError').hidden=true;setAudio();$('editDialog').showModal();tab(false);layoutWave();await detect(true);$('effectPreset').value=effectChanged()?'custom':'original';sync();},draw(){if(!$('editDialog').open||!source)return;if(!$('cutPane').hidden){drawWave($('editWave'),viewPeaks,null);const position=sourcePosition();$('editPlayhead').style.left=position/source.duration*100+'%';}},isWorking:()=>working};
}
