export function createLibraryUI({api,$,notice,fail,guarded,saved,updateScript,saveDraft,loadTakes,renderTakes,takeName,selected,setBusy,selectTake,allowed}){
 let data={scripts:[],projects:[]},active=null,timer,ready=false,queue=Promise.resolve(),detailsId=null,importJob=null;
 const pendingKey='voice-pending-scripts';const pending=()=>{try{return JSON.parse(localStorage.getItem(pendingKey)||'{}');}catch{return {};}};
 function stash(){const all=pending();all[active]=snapshot();localStorage.setItem(pendingKey,JSON.stringify(all));}
 const options=(id,items,empty,value)=>{const el=$(id);el.replaceChildren();if(empty!==null)el.add(new Option(empty,''));for(const item of items)el.add(new Option(item.title||item.name,item.id));el.value=value||'';};
 function lists(){options('scriptPicker',data.scripts,null,active);options('scriptProject',data.projects,'Ohne Projekt',$('scriptProject').value);options('takeProjectFilter',data.projects,'Alle Projekte',$('takeProjectFilter').value);}
 function show(script){active=script.id;$('script').value=script.text;$('scriptTitle').value=script.title;lists();$('scriptProject').value=script.projectId||'';updateScript();saveDraft();}
 function snapshot(){return {id:active,title:$('scriptTitle').value,text:$('script').value,projectId:$('scriptProject').value||null};}
 function flush(){clearTimeout(timer);if(!ready||!active)return queue;const value=snapshot();stash();const task=queue.catch(()=>{}).then(async()=>{const script=await api.saveScript(value);const all=pending();if(JSON.stringify(all[value.id])===JSON.stringify(value)){delete all[value.id];localStorage.setItem(pendingKey,JSON.stringify(all));}const i=data.scripts.findIndex(s=>s.id===script.id);if(i<0)data.scripts.push(script);else data.scripts[i]=script;options('scriptPicker',data.scripts,null,active);$('draftState').textContent='Script gespeichert';});queue=task;return task;}
 function scheduleSave(){if(!ready)return;try{stash();}catch(e){fail(e);}$('draftState').textContent='Wird gespeichert …';clearTimeout(timer);timer=setTimeout(()=>void flush().catch(fail),450);}
 $('scriptTitle').oninput=scheduleSave;$('scriptProject').onchange=scheduleSave;
 $('scriptPicker').onchange=guarded(async()=>{const id=$('scriptPicker').value;await flush();show(data.scripts.find(s=>s.id===id));});
 $('newScript').onclick=guarded(async()=>{await flush();const script=await api.saveScript({title:'Neues Script',text:'',projectId:$('scriptProject').value||null});data.scripts.push(script);show(script);$('scriptTitle').focus();$('scriptTitle').select();});
 $('deleteScript').onclick=guarded(async()=>{await flush();if(!await api.removeScript(active))return;data=await api.library();if(!data.scripts.length)data.scripts.push(await api.saveScript({title:'Mein Script',text:''}));show(data.scripts[0]);await loadTakes();});
 $('newProject').onclick=()=>{$('projectName').value='';$('projectError').textContent='';$('projectDialog').showModal();$('projectName').focus();};$('closeProject').onclick=()=>$('projectDialog').close();
 $('createProject').onclick=async()=>{try{const p=await api.saveProject({name:$('projectName').value});data=await api.library();lists();$('scriptProject').value=p.id;await flush();$('projectDialog').close();}catch(e){$('projectError').textContent=e.message;}};
 $('takeSearch').oninput=renderTakes;$('takeProjectFilter').onchange=renderTakes;$('favoriteFilter').onclick=()=>{const active=$('favoriteFilter').getAttribute('aria-pressed')!=='true';$('favoriteFilter').setAttribute('aria-pressed',String(active));$('favoriteFilter').textContent=active?'★':'☆';renderTakes();};
 function detailState(){const p=data.projects.find(p=>p.id===$('takeProject').value);$('linkBrinkProject').disabled=!p;$('sendToBrink').disabled=!p?.linked;$('takeDetailsStatus').textContent=p?.linked?'BRINK-Projektordner verbunden':p?'Projekt ist noch nicht mit einem BRINK-Ordner verbunden.':'Wähle ein Projekt für die Übergabe an BRINK.';}
 $('takeProject').onchange=detailState;
 $('libraryDetails').onclick=()=>{const take=selected();if(!take||!allowed())return;detailsId=take.id;$('takeNameInput').value=takeName(take);$('takeFavorite').checked=!!take.favorite;options('takeScript',data.scripts,'Ohne Script',take.scriptId);options('takeProject',data.projects,'Ohne Projekt',take.projectId);detailState();$('takeDetailsDialog').showModal();};
 $('closeTakeDetails').onclick=()=>$('takeDetailsDialog').close();
 async function saveDetails(){await api.updateTake(detailsId,{name:$('takeNameInput').value,favorite:$('takeFavorite').checked,scriptId:$('takeScript').value||null,projectId:$('takeProject').value||null});await loadTakes();}
 const detailAction=fn=>async()=>{try{await fn();}catch(e){$('takeDetailsStatus').textContent=e.message;}};
 $('saveTakeDetails').onclick=detailAction(async()=>{await saveDetails();$('takeDetailsDialog').close();notice('Take gespeichert.');});
 $('linkBrinkProject').onclick=detailAction(async()=>{await api.linkProject($('takeProject').value);data=await api.library();detailState();});
 $('sendToBrink').onclick=detailAction(async()=>{await saveDetails();const result=await api.handoff(detailsId,$('takeProject').value);$('takeDetailsStatus').textContent=`An BRINK übergeben: ${result.name}`;});
 $('exportCine').onclick=detailAction(async()=>{await saveDetails();if(await api.exportCine(detailsId))$('takeDetailsStatus').textContent='CINE-Projekt mit Voice-over gespeichert.';});
 $('cancelImport').onclick=()=>{if(importJob)void api.cancelJob(importJob);};$('jobDialog').addEventListener('cancel',e=>{e.preventDefault();if(importJob)void api.cancelJob(importJob);});
 $('importAudio').onclick=guarded(async()=>{if(!allowed())return;setBusy(true);try{const result=await api.importAudio();if(!result)return;importJob=result.jobId;$('importProgressBar').value=0;$('jobDialog').showModal();while(true){const job=await api.jobStatus(importJob);$('importProgress').textContent=job.label;$('importProgressBar').value=job.progress;if(job.state==='done'){const takes=await loadTakes();await selectTake(takes.find(t=>t.id===job.result.id));notice('Audio importiert und als Take gespeichert.');break;}if(job.state==='cancelled'){notice('Import abgebrochen.');break;}if(job.state==='error')throw Error(job.error);await new Promise(r=>setTimeout(r,100));}}finally{importJob=null;$('jobDialog').close();setBusy(false);}});
 return {async openScript(id){await flush();data=await api.library();const script=data.scripts.find(s=>s.id===id);if(!script)throw Error('Script nicht gefunden.');show(script);},async init(){data=await api.library();for(const value of Object.values(pending())){if(data.scripts.some(s=>s.id===value.id))await api.saveScript(value);}localStorage.removeItem(pendingKey);data=await api.library();if(!data.scripts.length)data.scripts.push(await api.saveScript({title:'Mein Script',text:saved.text||''}));show(data.scripts.find(s=>s.id===saved.activeScriptId)||data.scripts[0]);ready=true;},activeId:()=>active,flush,scheduleSave,async associate(id){const script=data.scripts.find(s=>s.id===active);await api.updateTake(id,{scriptId:active,projectId:script?.projectId||null});},filter(takes){const search=$('takeSearch').value.trim().toLocaleLowerCase(),project=$('takeProjectFilter').value,favorites=$('favoriteFilter').getAttribute('aria-pressed')==='true';return takes.filter(t=>(!search||takeName(t).toLocaleLowerCase().includes(search))&&(!project||t.projectId===project)&&(!favorites||t.favorite));},sync(locked){for(const id of ['scriptPicker','scriptTitle','scriptProject','newScript','deleteScript','newProject','importAudio'])$(id).disabled=locked;}};
}
