export function createTranscriptionUI({api,$,takeName,onScript,setBusy}){
 let take=null,document=null,working=false,loading=false,available=false,jobId=null,timer,queue=Promise.resolve(),generation=0;
 const pendingKey=id=>'voice-transcript-draft-'+id;
 function status(state,text){$('transcriptionStatus').dataset.state=state;$('transcriptionStatus').textContent=text;}
 function error(e){$('transcriptionError').hidden=false;$('transcriptionError').textContent=e.message||String(e);}
 function sync(){const locked=working||loading,hasText=!!$('transcriptionText').value.trim();$('closeTranscription').disabled=locked;$('startTranscription').disabled=locked||!available;$('startTranscription').textContent=document?'Neu transkribieren':'Transkribieren';$('transcriptionLanguage').disabled=locked;$('cancelTranscription').hidden=!working||!jobId;$('transcriptionProgress').hidden=!working;$('transcriptionText').disabled=locked||!document;for(const id of ['copyTranscription','exportTranscription','scriptTranscription'])$(id).disabled=locked||!document||!hasText;}
 function flush(){clearTimeout(timer);if(!take||!document)return queue;const id=take.id,text=$('transcriptionText').value;const task=queue.catch(()=>{}).then(async()=>{const saved=await api.transcriptionSave(id,text);if(localStorage.getItem(pendingKey(id))===text)localStorage.removeItem(pendingKey(id));if(take?.id===id){document=saved;if($('transcriptionText').value===text)$('transcriptionSaveState').textContent='Transkript gespeichert';}});queue=task;return task;}
 $('transcriptionText').oninput=()=>{try{localStorage.setItem(pendingKey(take.id),$('transcriptionText').value);$('transcriptionSaveState').textContent='Wird gespeichert …';clearTimeout(timer);timer=setTimeout(()=>void flush().catch(error),450);sync();}catch(e){error(e);}};
 $('transcriptionLanguage').onchange=()=>{localStorage.setItem('voice-transcription-language',$('transcriptionLanguage').value);};
 async function close(){if(working||loading)return;loading=true;sync();try{await flush();generation++;$('transcriptionDialog').close();}catch(e){error(e);}finally{loading=false;sync();}}$('closeTranscription').onclick=close;$('transcriptionDialog').addEventListener('cancel',e=>{e.preventDefault();void close();});
 $('startTranscription').onclick=async()=>{if(working||!take||!available)return;working=true;setBusy(true);$('transcriptionError').hidden=true;status('busy','Whisper wird vorbereitet …');$('transcriptionProgress').value=0;sync();try{await flush();const started=await api.transcriptionStart(take.id,$('transcriptionLanguage').value);if(!started){status('ready','Das bisherige Transkript bleibt erhalten.');return;}jobId=started.jobId;sync();while(true){const job=await api.transcriptionStatus(jobId);$('transcriptionProgress').value=job.progress;status('busy',`${job.label} · ${Math.round(job.progress*100)} %`);if(job.state==='done'){document=job.result;$('transcriptionText').value=document.text;localStorage.removeItem(pendingKey(take.id));$('transcriptionSaveState').textContent='Transkript gespeichert';status(document.text?'success':'empty',document.text?'Transkript bereit. Du kannst den Text jetzt bearbeiten.':'Keine Sprache erkannt. Prüfe den Take oder wähle die Sprache manuell.');break;}if(job.state==='cancelled'){status('ready','Transkription abgebrochen.');break;}if(job.state==='error')throw Error(job.error);await new Promise(r=>setTimeout(r,120));}}catch(e){status('error','Transkription nicht abgeschlossen');error(e);}finally{working=false;jobId=null;setBusy(false);sync();}};
 $('cancelTranscription').onclick=async()=>{if(jobId){$('cancelTranscription').disabled=true;try{await api.transcriptionCancel(jobId);}catch(e){error(e);}finally{$('cancelTranscription').disabled=false;}}};
 const action=fn=>async()=>{if(working||loading)return;loading=true;sync();try{await flush();await fn();}catch(e){error(e);}finally{loading=false;sync();}};
 $('copyTranscription').onclick=action(async()=>{await api.transcriptionCopy(take.id);status('success','Text in die Zwischenablage kopiert.');});
 $('exportTranscription').onclick=action(async()=>{if(await api.transcriptionExport(take.id))status('success','Transkript als TXT exportiert.');});
 $('scriptTranscription').onclick=action(async()=>{await onScript(take.id);generation++;$('transcriptionDialog').close();});
 return {async open(selected){if(working)return;take=selected;document=null;available=false;loading=true;const epoch=++generation;$('transcriptionText').value='';$('transcriptionError').hidden=true;$('transcriptionTake').textContent=takeName(take);$('transcriptionSaveState').textContent='Noch kein Transkript';$('transcriptionLanguage').value=localStorage.getItem('voice-transcription-language')||'de';if(!$('transcriptionLanguage').value)$('transcriptionLanguage').value='de';status('busy','Whisper wird geprüft …');sync();$('transcriptionDialog').showModal();try{const [info,stored]=await Promise.all([api.transcriptionInfo(),api.transcriptionGet(take.id)]);if(epoch!==generation)return;available=info.available;document=stored;if(stored){const pending=localStorage.getItem(pendingKey(take.id));$('transcriptionText').value=pending??stored.text;$('transcriptionSaveState').textContent=pending===null?'Transkript gespeichert':'Entwurf wiederhergestellt';if(pending!==null)await flush();}status(available?'ready':'error',available?stored?'Gespeichertes Transkript · lokal mit Whisper erkannt':'Whisper ist bereit. Wähle die Sprache und starte die Transkription.':info.message);}catch(e){status('error','Transkript konnte nicht geladen werden');error(e);}finally{loading=false;sync();}}};
}
